lane_follower:
  ros__parameters:
    update_rate: 10.0
    control_rate: 60.0
    target_speed: 0.0
    target_acceleration: 1.0
    image_topic: /sensing/camera/traffic_light/image_raw
    control_topic: /control/command/control_cmd
    gear_topic: /control/command/gear_cmd
    turn_indicator_topic: /control/command/turn_indicators_cmd
    hazard_light_topic: /control/command/hazard_lights_cmd
    emergency_topic: /control/command/emergency_cmd
    control_mode_service: input/control_mode_request
    publish_debug_image: true